version: 0.2

phases:
  build:
    commands:
      - echo starting build
      - mvn clean package
     post_build:
      commands:
        - echo the has successfully build
        
artifacts:
  files:
    - target/test-service.jar
  discard-paths: yes
